name: "CDK Deploy"

# Trigger when commits are pushed to the master branch
on:
  push:
    branches: [ master ]

jobs:
  terraform-plan:
    name: "CDK Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: '*'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.IA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KA }}
          AWS_DEFAULT_REGION: 'us-east-1'
