name: "CDK synth"

# Trigger when a pull request is received
on:
  pull_request:
    types: [ opened ]

jobs:
  cdk-synth:
    name: "AWS CDK Synth"
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # Provides AWS credentials to AWS CDK
      # By default, CDK checks the home directory for a .aws folder with a credential file
      # Documentation: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/create-shared-credentials-file.html
      - name: "Setup - Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.IA }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.KA }}" >> ~/.aws/credentials

      - name: "Installing dependencies from requirements.txt"
        run: python -m pip install -r requirements.txt

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Installing AWS CDK"
        run: npm install -g aws-cdk

      - name: "Run cdk synth"
        id: synth
        run: cdk synth --json EventBridgeAwsCdkStack | grep Type 2>&1 | tee cdk.log

      - name: Add synth comment to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
        run: |
              jq --raw-input --slurp '{body: .}' cdk.log > cdk.json
              curl \
                -H "Content-Type: application/json" \
                -H "Authorization: token $GITHUB_TOKEN" \
                -d @cdk.json \
                -X POST \
                $URL

      - name: Run CDK diff
        run: cdk diff -c aws-cdk:enableDiffNoFail=true --no-color --app cdk.out "*" 2>&1 | tee cdk1.log

      - name: Add diff comment to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
        run: |
              jq --raw-input --slurp '{body: .}' cdk1.log > cdk1.json
              curl \
                -H "Content-Type: application/json" \
                -H "Authorization: token $GITHUB_TOKEN" \
                -d @cdk1.json \
                -X POST \
                $URL

      #   run: |
      #         cdk synth --output=./templates
      #         echo "##[set-output name=stdoutplan;]$(<./templates/EventBridgeAwsCdkStack.template.json)"
      #
      # - name: "Run - CDK synth Comment"
      #   uses: actions/github-script@0.9.0
      #   env:
      #     STDOUT: "```${{ steps.synth.outputs.stdoutplan }}```"
      #   with:
      #     github-token: ${{ secrets.GIT_PAT }}
      #     script: |
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: process.env.STDOUT
      #       })
