name: "CDK synth"

# Trigger when a pull request is received
on:
  pull_request:
    types: [ opened ]

jobs:
  cdk-synth:
    name: "AWS CDK Synth"
    runs-on: ubuntu-latest
    steps:
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.IA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KA }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_version: 'latest'
          working_dir: '.'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.IA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KA }}
          AWS_DEFAULT_REGION: 'us-east-1'
